export const CATALOGS_GET_PENDING = 'CATALOGS_GET_PENDING'
export const CATALOGS_GET_SUCCESS = 'CATALOGS_GET_SUCCESS'
export const CATALOGS_GET_FAILURE = 'CATALOGS_GET_FAILURE'

export const CATALOGS_GET_METRICS_PENDING = 'CATALOGS_GET_METRICS_PENDING'
export const CATALOGS_GET_METRICS_SUCCESS = 'CATALOGS_GET_METRICS_SUCCESS'
export const CATALOGS_GET_METRICS_FAILURE = 'CATALOGS_GET_METRICS_FAILURE'
