export const CATALOGS_GET_PENDING = 'CATALOGS_GET_PENDING'
export const CATALOGS_GET_SUCCESS = 'CATALOGS_GET_SUCCESS'
export const CATALOGS_GET_FAILURE = 'CATALOGS_GET_FAILURE'

export const CATALOGS_GET_METRICS_PENDING = 'CATALOGS_GET_METRICS_PENDING'
export const CATALOGS_GET_METRICS_SUCCESS = 'CATALOGS_GET_METRICS_SUCCESS'
export const CATALOGS_GET_METRICS_FAILURE = 'CATALOGS_GET_METRICS_FAILURE'

export const CATALOGS_GET_HARVESTS_PENDING = 'CATALOGS_GET_HARVESTS_PENDING'
export const CATALOGS_GET_HARVESTS_SUCCESS = 'CATALOGS_GET_HARVESTS_SUCCESS'
export const CATALOGS_GET_HARVESTS_FAILURE = 'CATALOGS_GET_HARVESTS_FAILURE'

export const CATALOGS_SYNC_PENDING = 'CATALOGS_SYNC_PENDING'
export const CATALOGS_SYNC_SUCCESS = 'CATALOGS_SYNC_SUCCESS'
export const CATALOGS_SYNC_FAILURE = 'CATALOGS_SYNC_FAILURE'

export const HARVESTS_GET_PENDING = 'HARVESTS_GET_PENDING'
export const HARVESTS_GET_SUCCESS = 'HARVESTS_GET_SUCCESS'
export const HARVESTS_GET_FAILURE = 'HARVESTS_GET_FAILURE'
