export const topicCategories = {
  farming: 'agriculture',
  biota: 'biota',
  boundaries: 'limites',
  climatologyMeteorologyAtmosphere: 'climatologie météorologie atmosphère',
  economy: 'économie',
  elevation: 'élévation',
  environment: 'environnement',
  geoscientificInformation: 'informations géoscientifiques',
  health: 'santé',
  imageryBaseMapsEarthCover: 'Imagerie',
  intelligenceMilitary: 'intelligence militaire',
  inlandWaters: 'eaux intérieures',
  location: 'emplacement',
  oceans: 'océans',
  planningCadastre: 'planification du cadastre',
  society: 'société',
  structure: 'structure',
  transportation: 'transport',
  utilitiesCommunication: 'utilitaires communication',
}
